function [Results] = SPF_NESTED_P2_Simulate(EnvironmentCfg,ScenarioCfg)
EnvironmentCfg.SourcesCfg=...
    SPF_AssignSignalsToSources(...
    EnvironmentCfg.SourcesCfg,...
    ScenarioCfg ...
    );
EnvironmentCfg.SensorsCfg=...
    SPF_PORAT91_AssignFiltersToSensors(...
    EnvironmentCfg.SensorsCfg, ...
    [] ...FilterCfg ...
    );
[InputSig_CellArr_Noised] = SPF_GenInput(EnvironmentCfg,ScenarioCfg);
end