function [max_Range] = SPF_ResolveEnvMaxRange(EnvironmentCfg)
f_fetch_ranges=...
    @(RefPoint,Points) ...
    cellfun( ...
    @(Point) sqrt(sum((RefPoint-Point).^2)), ...
    Points ...
    );
SourceToSensorRanges_CellArr=cellfun(...
    @(Sensor) f_fetch_ranges(Sensor,EnvironmentCfg.SourcesCfg), ...
    EnvironmentCfg.SensorsCfg, ...
    'UniformOutput',false ...
    );
SourceToSensorRanges_Vec=cell2mat(...
    reshape(...
    cellfun( ...
    @(X) X(:), ...
    SourceToSensorRanges_CellArr,...
    'UniformOutput',false ...
    ),...
    [],1) ...
    );
max_Range=max(SourceToSensorRanges_Vec);
end

