function [] = SPF_PlotEnvironment(EnvCfg)
SensorPosMAT= ...
    cell2mat(...
    cellfun(...
    @(SensorCfg) ...
    SensorCfg.Position,EnvCfg.SensorsCfg, ...
    'UniformOutput',false ...
    ) ...
    );
SensorPosMAT_X=SensorPosMAT(1,:);
SensorPosMAT_Y=SensorPosMAT(2,:);
SensorPosMAT_Z=SensorPosMAT(3,:);
figure;stem3(SensorPosMAT_X,SensorPosMAT_Y,SensorPosMAT_Z,'o');
title('All sensors');
xlabel('X axis');
ylabel('Y axis');
zlabel('Z axis');
axis square;
end

