function [SourcesCfg] = SPF_PORAT91_AssignSignalsToSources(SourcesCfg,ScenarioCfg)
nSrc=numel(SourcesCfg);
AmpOpt=-3:2:3;
nOpt=length(AmpOpt);
for SrcID=1:nSrc
    SourcesCfg{SrcID}.Signal=...
        reshape(...
        AmpOpt(randi(nOpt,ScenarioCfg.nSnapshots,1)) ...
        + ...
        1i*AmpOpt(randi(nOpt,ScenarioCfg.nSnapshots,1)) ...
        ,[],1 ...
        );
end
end